baseURL = 'https://raycadle.github.io/'
languageCode = 'en-us'
title = "Ray Cadle"
theme = "PaperMod"

disableKinds = ["RSS"]

[author]
  name = "Ray Cadle"
  email = "hiii@raycadle.com"

[params]
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowCodeCopyButtons = true

[params.profileMode]
  enabled = true
  title = "✌️ Yo, I'm Ray!"
  subtitle = "Learner • Car Nerd • Breaker of Things"
  imageUrl = "images/avatar.png"
  imageWidth = 160
  imageHeight = 160
  
  [[params.profileMode.buttons]]
    name = "Notebook"
    url = "https://raycadle.github.io/notebook"
    
  [[params.profileMode.buttons]]
    name = "Projects"
    url = "https://github.com/raycadle?tab=repositories"

[params.assets]
  css = ["css/custom/custom.css"]
  favicons = "favicon.ico"

[menu]
  [[menu.main]]
    identifier = "notebook"
    name = "Notebook"
    url = "https://raycadle.github.io/notebook"
    weight = 10
    
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "https://github.com/raycadle?tab=repositories"
    weight = 10
